plot_properties = (
    'aa',
    'alpha',
    'color',
    'dash_capstyle',
    'dash_joinstyle',
    'fillstyle',
    'label',
    'linestyle',
    'linewidth',
    'marker',
    'markeredgecolor',
    'markeredgewidth',
    'markerfacecolor',
    'markerfacecoloralt',
    'solid_capstyle',
    'solid_joinstyle',
    'url',
    'visible',
    'zorder',
    )

scatter_properties = (
    'alpha',
    'dashes',
    'edgecolor',
    'facecolor',
    'label',
    'linestyle',
    'linewidth',
    'sizes',
    'urls',
    'visible',
    'zorder',
    )

axes_properties = (
    'adjustable',
    'alpha',
    'anchor',
    'animated',
    'aspect',
    'autoscale_on',
    'autoscalex_on',
    'autoscaley_on',
    'axes',
    'axis_bgcolor',
    'axisbelow',
#    'children',
    'clip_box',
    'clip_on',
    'clip_path',
    'contains',
    'cursor_props',
    'data_ratio',
    'figure',
    'frame',
    'frame_on',
    'geometry',
    'gid',
    'images',
    'label',
    'legend',
    'legend_handles_labels',
    'lines',
    'navigate',
    'navigate_mode',
    'rasterized',
    'snap',
    'title',
    'url',
    'visible',
    'xbound',
    'xlabel',
    'xlim',
    'xscale',
    'ybound',
    'ylabel',
    'ylim',
    'yscale',
    'zorder')

figure_properties = (
    'alpha',
    'animated',
    'axes',
    'children',
    'clip_box',
    'clip_on',
    'clip_path',
    'dpi',
    'edgecolor',
    'facecolor',
    'figheight',
    'figwidth',
    'frameon',
    'gid',
    'label',
    'rasterized',
    'snap',
    'url',
    'visible',
    'zorder')

rect_properties = (
    'alpha', 'ec', 'fc', 'fill', 'hatch', 'ls', 'lw', 'visible',
    'zorder')
